// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gen "github.com/leabago/share-radio/adder/docs/gen"
)

// MockStation is a mock of Station interface.
type MockStation struct {
	ctrl     *gomock.Controller
	recorder *MockStationMockRecorder
}

// MockStationMockRecorder is the mock recorder for MockStation.
type MockStationMockRecorder struct {
	mock *MockStation
}

// NewMockStation creates a new mock instance.
func NewMockStation(ctrl *gomock.Controller) *MockStation {
	mock := &MockStation{ctrl: ctrl}
	mock.recorder = &MockStationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStation) EXPECT() *MockStationMockRecorder {
	return m.recorder
}

// CreateStation mocks base method.
func (m *MockStation) CreateStation(ctx context.Context, request gen.CreateStationRequestObject) (gen.StationId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStation", ctx, request)
	ret0, _ := ret[0].(gen.StationId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStation indicates an expected call of CreateStation.
func (mr *MockStationMockRecorder) CreateStation(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStation", reflect.TypeOf((*MockStation)(nil).CreateStation), ctx, request)
}

// GetStation mocks base method.
func (m *MockStation) GetStation(ctx context.Context, request gen.GetStationRequestObject) (gen.Station, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStation", ctx, request)
	ret0, _ := ret[0].(gen.Station)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStation indicates an expected call of GetStation.
func (mr *MockStationMockRecorder) GetStation(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStation", reflect.TypeOf((*MockStation)(nil).GetStation), ctx, request)
}

// ListStations mocks base method.
func (m *MockStation) ListStations(ctx context.Context, request gen.ListStationsRequestObject) (gen.StationListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStations", ctx, request)
	ret0, _ := ret[0].(gen.StationListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStations indicates an expected call of ListStations.
func (mr *MockStationMockRecorder) ListStations(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStations", reflect.TypeOf((*MockStation)(nil).ListStations), ctx, request)
}

// MockGenre is a mock of Genre interface.
type MockGenre struct {
	ctrl     *gomock.Controller
	recorder *MockGenreMockRecorder
}

// MockGenreMockRecorder is the mock recorder for MockGenre.
type MockGenreMockRecorder struct {
	mock *MockGenre
}

// NewMockGenre creates a new mock instance.
func NewMockGenre(ctrl *gomock.Controller) *MockGenre {
	mock := &MockGenre{ctrl: ctrl}
	mock.recorder = &MockGenreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenre) EXPECT() *MockGenreMockRecorder {
	return m.recorder
}

// ListGenres mocks base method.
func (m *MockGenre) ListGenres(ctx context.Context, request gen.ListGenresRequestObject) (gen.GenreList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGenres", ctx, request)
	ret0, _ := ret[0].(gen.GenreList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGenres indicates an expected call of ListGenres.
func (mr *MockGenreMockRecorder) ListGenres(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGenres", reflect.TypeOf((*MockGenre)(nil).ListGenres), ctx, request)
}

// MockLanguage is a mock of Language interface.
type MockLanguage struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageMockRecorder
}

// MockLanguageMockRecorder is the mock recorder for MockLanguage.
type MockLanguageMockRecorder struct {
	mock *MockLanguage
}

// NewMockLanguage creates a new mock instance.
func NewMockLanguage(ctrl *gomock.Controller) *MockLanguage {
	mock := &MockLanguage{ctrl: ctrl}
	mock.recorder = &MockLanguageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguage) EXPECT() *MockLanguageMockRecorder {
	return m.recorder
}

// ListLanguages mocks base method.
func (m *MockLanguage) ListLanguages(ctx context.Context, request gen.ListLanguagesRequestObject) (gen.LanguageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx, request)
	ret0, _ := ret[0].(gen.LanguageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockLanguageMockRecorder) ListLanguages(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockLanguage)(nil).ListLanguages), ctx, request)
}
