// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gen "github.com/leabago/share-radio/adder/docs/gen"
	entity "github.com/leabago/share-radio/adder/internal/entity"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, userID string) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, userID)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(ctx context.Context, userID string, t entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(ctx, userID, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), ctx, userID, t)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(ctx context.Context, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), ctx, t)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaskRepo) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepoMockRecorder) Delete(ctx, userID, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepo)(nil).Delete), ctx, userID, taskID)
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, userID, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTaskRepo) List(ctx context.Context, userID string, filter entity.TaskFilter) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepoMockRecorder) List(ctx, userID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepo)(nil).List), ctx, userID, filter)
}

// Store mocks base method.
func (m *MockTaskRepo) Store(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTaskRepoMockRecorder) Store(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTaskRepo)(nil).Store), ctx, task)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, task)
}

// MockStationRepo is a mock of StationRepo interface.
type MockStationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStationRepoMockRecorder
}

// MockStationRepoMockRecorder is the mock recorder for MockStationRepo.
type MockStationRepoMockRecorder struct {
	mock *MockStationRepo
}

// NewMockStationRepo creates a new mock instance.
func NewMockStationRepo(ctrl *gomock.Controller) *MockStationRepo {
	mock := &MockStationRepo{ctrl: ctrl}
	mock.recorder = &MockStationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStationRepo) EXPECT() *MockStationRepoMockRecorder {
	return m.recorder
}

// CreateStation mocks base method.
func (m *MockStationRepo) CreateStation(ctx context.Context, station *entity.Station) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStation", ctx, station)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStation indicates an expected call of CreateStation.
func (mr *MockStationRepoMockRecorder) CreateStation(ctx, station interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStation", reflect.TypeOf((*MockStationRepo)(nil).CreateStation), ctx, station)
}

// GetStation mocks base method.
func (m *MockStationRepo) GetStation(ctx context.Context, id string) (entity.Station, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStation", ctx, id)
	ret0, _ := ret[0].(entity.Station)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStation indicates an expected call of GetStation.
func (mr *MockStationRepoMockRecorder) GetStation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStation", reflect.TypeOf((*MockStationRepo)(nil).GetStation), ctx, id)
}

// ListStations mocks base method.
func (m *MockStationRepo) ListStations(ctx context.Context, request gen.ListStationsRequestObject) ([]entity.Station, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStations", ctx, request)
	ret0, _ := ret[0].([]entity.Station)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStations indicates an expected call of ListStations.
func (mr *MockStationRepoMockRecorder) ListStations(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStations", reflect.TypeOf((*MockStationRepo)(nil).ListStations), ctx, request)
}

// MockGenreRepo is a mock of GenreRepo interface.
type MockGenreRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGenreRepoMockRecorder
}

// MockGenreRepoMockRecorder is the mock recorder for MockGenreRepo.
type MockGenreRepoMockRecorder struct {
	mock *MockGenreRepo
}

// NewMockGenreRepo creates a new mock instance.
func NewMockGenreRepo(ctrl *gomock.Controller) *MockGenreRepo {
	mock := &MockGenreRepo{ctrl: ctrl}
	mock.recorder = &MockGenreRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenreRepo) EXPECT() *MockGenreRepoMockRecorder {
	return m.recorder
}

// ListGenres mocks base method.
func (m *MockGenreRepo) ListGenres(ctx context.Context) ([]entity.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGenres", ctx)
	ret0, _ := ret[0].([]entity.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGenres indicates an expected call of ListGenres.
func (mr *MockGenreRepoMockRecorder) ListGenres(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGenres", reflect.TypeOf((*MockGenreRepo)(nil).ListGenres), ctx)
}

// MockLanguageRepo is a mock of LanguageRepo interface.
type MockLanguageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageRepoMockRecorder
}

// MockLanguageRepoMockRecorder is the mock recorder for MockLanguageRepo.
type MockLanguageRepoMockRecorder struct {
	mock *MockLanguageRepo
}

// NewMockLanguageRepo creates a new mock instance.
func NewMockLanguageRepo(ctrl *gomock.Controller) *MockLanguageRepo {
	mock := &MockLanguageRepo{ctrl: ctrl}
	mock.recorder = &MockLanguageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguageRepo) EXPECT() *MockLanguageRepoMockRecorder {
	return m.recorder
}

// ListLanguages mocks base method.
func (m *MockLanguageRepo) ListLanguages(ctx context.Context) ([]entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx)
	ret0, _ := ret[0].([]entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockLanguageRepoMockRecorder) ListLanguages(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockLanguageRepo)(nil).ListLanguages), ctx)
}
